Remove expensive dependencies
We probably don't need charset detection, it's expensive and heuristic:

[3] pry(main)> CharDet.detect("moi")
=> {"encoding"=>"ascii", "confidence"=>1.0}
[4] pry(main)> CharDet.detect("moiä")
=> {"encoding"=>"EUC-KR", "confidence"=>0.99}
[5] pry(main)> CharDet.detect("moiäö")
=> {"encoding"=>"utf-8", "confidence"=>0.7525}

Forcing UTF8 probably is good enough:

[1] pry(main)> "moi\255".split
ArgumentError: invalid byte sequence in UTF-8
from (pry):1:in `split'
[2] pry(main)> "moi\255".encode("UTF-8", invalid: :replace).split
=> ["moi�"]

If we actually need to support other charset, we need to allow either global or
node level configuration of charset.